config:
  send_anonymous_usage_stats: False

# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: dbt.duckdb
      schema: main
    prd:
      type: duckdb
      path: dbt.duckdb
      schema: prd
